spring: 
  profiles: 
    active: dev



---
server:
  port: 8001

#  mybaits config
mybatis:
  type-aliases-package: com.company.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring config
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qaz@WSX

#配置eureka， 把我们这个服务提供者，注册到eureka服务器上
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001  # 修改该服务提供者 在Eureka server上的描述
    prefer-ip-address: true    #显示具体服务实例的IP
#acturator config info , 告诉别人这个微服务是干什么用的
info:
  app.name: springcloud-provider
  company.name: company-name


---
server:
  port: 8001

#  mybaits config
mybatis:
  type-aliases-package: com.company.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring config
spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qaz@WSX

#配置eureka， 把我们这个服务提供者，注册到eureka服务器上
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001  # 修改该服务提供者 在Eureka server上的描述
    prefer-ip-address: true    #显示具体服务实例的IP
#acturator config info , 告诉别人这个微服务是干什么用的
info:
  app.name: springcloud-provider
  company.name: company-name

